export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';